apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpasetup
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vpasetup-role
  namespace: kube-system
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpasetup-clusterrole
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vpasetup-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vpasetup-role
subjects:
- kind: ServiceAccount
  name: vpasetup
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vpasetup-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vpasetup-clusterrole
subjects:
- kind: ServiceAccount
  name: vpasetup
  namespace: kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vpasetup
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: vpatest
          image: <IMAGE_REPONAME>:<TAG>   ## CHANGE THIS
          env:
            - name: API_SERVER
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
      restartPolicy: Never
      serviceAccountName: vpasetup