apiVersion: v1
kind: Pod
metadata:
  name: pv-reader
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: reader
    volumeMounts:
    - mountPath: /data/reader
      name: pv-vol
      readOnly: true
  restartPolicy: Always
  volumes:
    - name: pv-vol
      persistentVolumeClaim: 
        claimName: dynamic-pvc