apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-hunt
mountOptions:
- debug
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true