apiVersion: v1
kind: Pod
metadata:
  name: jenkins-busybox
spec:
  serviceAccountName: jenkins-sa
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: debug-busybox
spec:
  serviceAccountName: debug-sa
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always