apiVersion: v1
kind: LimitRange
metadata:
  name: compute-limit-range
  namespace: microservices
  labels:
    app.kubernetes.io/name: microservices
    app.kubernetes.io/part-of: components
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/created-by: controller-manager
spec:
  limits:
  - max:
      cpu: "100m"
      memory: "100Mi"
    min:
      cpu: "100m"
      memory: "100Mi"
    type: Container
