apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-quota-namespace
  namespace: microservices
  labels:
    app.kubernetes.io/name: microservices
    app.kubernetes.io/part-of: components
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/created-by: controller-manager
spec:
   hard:
     configmaps: "10"
     persistentvolumeclaims: "4"
     pods: "4"
     replicationcontrollers: "20"
     secrets: "10"
     services: "10"
     services.loadbalancers: "2"
