apiVersion: v1
kind: Pod
metadata:
   name: nginx
   namespace: microservices
   labels:
      app.kubernetes.io/name: microservices
      app.kubernetes.io/part-of: components
      app.kubernetes.io/managed-by: helm
      app.kubernetes.io/created-by: controller-manager
spec:
   containers:
   - name: nginx
     image: nginx:latest
     resources:
       requests:
         memory: "100Mi"
         cpu: "100m"
       limits:
         memory: "100Mi"
         cpu: "100m"
