apiVersion: v1
kind: ResourceQuota
metadata:
   name: compute-quota-namespace
   namespace: microservices
   labels:
     app.kubernetes.io/name: microservices
     app.kubernetes.io/part-of: components
     app.kubernetes.io/managed-by: helm
     app.kubernetes.io/created-by: controller-manager
spec:
  hard:
    requests.cpu: "100"
    requests.memory: 200Mi
    limits.cpu: "100"
    limits.memory: 200Mi
