apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: crendential-properties
      mountPath: "/etc/db"
      readOnly: true
  volumes:
  - name: crendential-properties
    secret:
      secretName: db-creds
  restartPolicy: Always