apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: reader
    volumeMounts:
    - mountPath: /data/reader
      name: shared-vol
      readOnly: true
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: writer
    volumeMounts:
    - mountPath: /data/writer
      name: shared-vol
  restartPolicy: Always
  volumes:
    - name: shared-vol
      emptyDir: {}