apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: ot-configs  
      mountPath: "/etc/config"
  volumes:
  - name: ot-configs
    configMap:
      name: ot-config
  restartPolicy: Always