apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    env:
      - name: USERNAME
        valueFrom:
          configMapKeyRef:
            name: attendance-config
            key: mysql_username
      - name: PASSWORD
        valueFrom:
          configMapKeyRef:
            name: attendance-config
            key: mysql_password
  restartPolicy: Always