apiVersion: v1
kind: Pod
metadata:
  name: busybox-writer
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: writer
    volumeMounts:
    - mountPath: /data/writer
      name: shared-vol
      readOnly: false
  restartPolicy: Always
  volumes:
    - name: shared-vol
      hostPath: 
        path: /data
        type: DirectoryOrCreate